# Generated by Django 3.2.7 on 2021-09-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=8, unique=True, verbose_name='Clave')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('dose', models.CharField(blank=True, max_length=30, verbose_name='Dosis')),
                ('presentation', models.CharField(blank=True, max_length=20, verbose_name='Presenta')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IVA')),
                ('more_info', models.CharField(blank=True, max_length=200, verbose_name='Información')),
                ('is_generic', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2)),
            ],
        ),
    ]
