# Generated by Django 3.2.7 on 2021-09-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_generic',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Genérico'),
        ),
    ]
