# Generated by Django 3.2.7 on 2021-09-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('products', '0002_alter_product_is_generic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='reject_reason',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Inactivo', 'Inactivo')], default='Pendiente', max_length=20, verbose_name='Estado de producto'),
        ),
    ]
