# Generated by Django 3.2.7 on 2021-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status_provider_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IEPS'),
        ),
    ]
