# Generated by Django 3.2.7 on 2021-09-27 23:53

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_ieps_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(default=products.models.generate_unique_key, max_length=8, unique=True, verbose_name='Clave'),
        ),
    ]
