# Generated by Django 3.2.7 on 2021-09-28 22:18

from django.db import migrations, models
import django.db.models.deletion


def create_initial_labs_and_categories(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    Category.objects.create(name='N/A')
    Laboratory = apps.get_model("products", "Laboratory")
    Laboratory.objects.create(name='N/A')


def reverse_create_initial_labs_and_categories(apps, schema_editor):
    Category = apps.get_model("products", "Category")
    Category.objects.filter(name="N/A").delete()
    Laboratory = apps.get_model("products", "Laboratory")
    Laboratory.objects.filter(name="N/A").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre del laboratorio')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_generic',
        ),
        migrations.RunPython(
            create_initial_labs_and_categories,
            reverse_create_initial_labs_and_categories),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='laboratory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.laboratory'),
            preserve_default=False,
        ),
    ]
