# Generated by Django 3.2.7 on 2021-09-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_category_and_lab_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Nombre de especie')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='active_substance',
            field=models.CharField(default='', max_length=150, verbose_name='Sustancia activa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='animal_groups',
            field=models.ManyToManyField(to='products.AnimalGroup'),
        ),
    ]
