# Generated by Django 3.2.7 on 2021-10-15 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_changepricerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ieps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='IEPS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA'),
        ),
    ]
