# Generated by Django 3.2.7 on 2021-10-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_limits_to_iva_and_ieps_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(max_length=20, unique=True, verbose_name='Clave'),
        ),
    ]
