# Generated by Django 3.2.7 on 2021-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='NE', max_length=2, verbose_name='Clave'),
        ),
    ]
