# Generated by Django 3.2.8 on 2021-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepricerequest',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado de la solicitud'),
        ),
    ]
