# Generated by Django 3.2.8 on 2021-11-07 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_provider_token_apply_date'),
        ('products', '0012_alter_changepricerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('presentation', models.CharField(blank=True, max_length=20, verbose_name='Presenta')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA')),
                ('ieps', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='IEPS')),
                ('more_info', models.CharField(blank=True, max_length=200, verbose_name='Información')),
                ('active_substance', models.CharField(max_length=150, verbose_name='Sustancia activa')),
                ('reject_reason', models.CharField(default='N/A', max_length=500)),
                ('status', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Inactivo', 'Inactivo')], default='Pendiente', max_length=20, verbose_name='Estado de petición')),
                ('animal_groups', models.ManyToManyField(to='products.AnimalGroup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.laboratory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA')),
                ('laboratory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.laboratory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
        ),
    ]
