# Generated by Django 3.2.8 on 2021-11-07 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211107_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprovider',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='productprovider',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.laboratory'),
        ),
        migrations.AlterField(
            model_name='productprovider',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
