# Generated by Django 3.2.8 on 2021-11-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211107_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reject_reason',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Inactivo', 'Inactivo')], default='Pendiente', max_length=20, verbose_name='Estado de petición'),
        ),
        migrations.DeleteModel(
            name='ProductRequest',
        ),
    ]
