# Generated by Django 3.2.8 on 2021-11-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_provider_token_apply_date'),
        ('products', '0016_auto_20211108_0710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprovider',
            unique_together={('product', 'provider')},
        ),
    ]
