# Generated by Django 3.2.10 on 2022-03-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_provider_token_apply_date'),
        ('products', '0019_productprovider_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprovider',
            unique_together={('product', 'provider')},
        ),
    ]
