version: 2.1

orbs:
  python: circleci/python@1.2
  jira: circleci/jira@1.3.1
  node: circleci/node@4.7.0
  ms-teams-notifier: oktapodia/ms-teams-notifier@3.0.0

workflows:
  gaqsa-pipeline:
    jobs:
      - backend-build-and-test:
          post-steps:
            - ms-teams-notifier/report:
                only_on_fail: true
                webhook_url: $MS_TEAMS_WEBHOOK_URL
            - jira/notify:
                environment_type: development
      - frontend-build-and-test:
          post-steps:
            - ms-teams-notifier/report:
                only_on_fail: true
                webhook_url: $MS_TEAMS_WEBHOOK_URL
            - jira/notify:
                environment_type: development
      - deploy-staging:
          requires:
            - frontend-build-and-test
            - backend-build-and-test
          filters:
            branches:
              only:
                - main
          post-steps:
            - ms-teams-notifier/report:
                only_on_fail: true
                webhook_url: $MS_TEAMS_WEBHOOK_URL
            - jira/notify:
                environment_type: staging
                job_type: deployment
      - wait-for-approval:
          type: approval
          requires:
            - deploy-staging
      - deploy-production:
          requires:
            - wait-for-approval
          filters:
            branches:
              only:
                - main
          post-steps:
            - ms-teams-notifier/report:
                only_on_fail: true
                webhook_url: $MS_TEAMS_WEBHOOK_URL
            - jira/notify:
                environment_type: production
                job_type: deployment
jobs:
  backend-build-and-test:
    docker:
      - image: cimg/python:3.8.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          app-dir: ./backend
      - run:
          name: Lint
          working_directory: ./backend
          command: |
            poetry run flake8 --exclude=*.pyc,venv/
      - run:
          name: Create test artifact folders
          command: |
            mkdir test-reports-html
            mkdir test-reports-xml
      - run:
          name: Run tests
          working_directory: ./backend
          command: |
            poetry run coverage run manage.py test
            poetry run coverage report --fail-under=80
            poetry run coverage html -d test-reports-html
            poetry run coverage xml -o test-reports-xml/coverage.xml
      - store_artifacts:
          path: test-reports-html
      - store_artifacts:
          path: test-reports-xml
      - store_test_results:
          path: test-reports-xml
  frontend-build-and-test:
    docker:
    - image: node:16
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          app-dir: ./frontend
          pkg-manager: yarn
      - run:
          name: Lint
          working_directory: ./frontend
          command: yarn lint
      - run:
          name: Typecheck
          working_directory: ./frontend
          command: yarn typecheck
      - run:
          name: test
          working_directory: ./frontend
          command: yarn test
      - run:
          name: build
          working_directory: ./frontend
          command: yarn build
      - persist_to_workspace:
          root: frontend
          paths:
            - build
  deploy-staging:
    docker:
      - image: cibuilds/hugo:0.42.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/frontend/build
      - run:
          name: Deploy to staging
          command: |
            ssh-keyscan -H gaqsa.com >> ~/.ssh/known_hosts
            ./scripts/deployment/staging/deploy_staging.sh gaqsacom@gaqsa.com backend /tmp/frontend/build/build
      - run:
          name: Run curl smoke tests
          command: |
            ./scripts/deployment/staging/smoke_test.sh https://api.staging.gaqsa.com/
            ./scripts/deployment/staging/smoke_test.sh https://staging.gaqsa.com/
  deploy-production:
    docker:
      - image: cibuilds/hugo:0.42.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/frontend/build
      - run:
          name: Deploy to production
          command: |
            ssh-keyscan -H gaqsa.com >> ~/.ssh/known_hosts
            ./scripts/deployment/production/deploy_production.sh gaqsacom@gaqsa.com backend /tmp/frontend/build/build
      - run:
          name: Run curl smoke tests
          command: |
            ./scripts/deployment/production/smoke_test.sh https://api.gaqsa.com/
            ./scripts/deployment/production/smoke_test.sh https://prod.gaqsa.com/