# Generated by Django 3.2.7 on 2021-09-23 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_add_ieps_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=8, unique=True, verbose_name='OrdenCompra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8, unique=True, verbose_name='Requisicion')),
                ('quantity_req', models.IntegerField()),
                ('quantity_acep', models.IntegerField(default=0)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchase_order')),
            ],
        ),
    ]
