# Generated by Django 3.2.7 on 2021-10-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
