# Generated by Django 3.2.8 on 2021-11-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='ending_at',
            field=models.DateField(),
        ),
    ]
