# Generated by Django 3.2.8 on 2021-11-09 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productprovider_unique_together'),
        ('offers', '0003_alter_offer_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AddField(
            model_name='offer',
            name='product_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productprovider'),
        ),
    ]
