# Generated by Django 3.2.8 on 2021-11-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productprovider_unique_together'),
        ('offers', '0004_auto_20211109_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productprovider'),
        ),
    ]
