# Generated by Django 3.2.7 on 2021-09-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='nulo@gmail.com', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
    ]
