# Generated by Django 3.2.7 on 2021-10-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='token',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='Token Cambio de Precio'),
        ),
        migrations.AddField(
            model_name='provider',
            name='token_used',
            field=models.BooleanField(default=False, verbose_name='Token Cambio de Precio Utilizado'),
        ),
    ]
