# Generated by Django 3.2.7 on 2021-10-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20211006_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.AddField(
            model_name='provider',
            name='dimension',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='provider',
            name='internal_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='nav_key',
            field=models.CharField(default='', max_length=100, verbose_name='Clave Nav'),
        ),
    ]
