# Generated by Django 3.2.7 on 2021-10-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20211021_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='invoice_telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
