# Generated by Django 3.2.7 on 2021-10-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_provider_invoice_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
    ]
