# Generated by Django 3.2.7 on 2021-09-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='purchase_order',
            new_name='order',
        ),
    ]
