# Generated by Django 3.2.7 on 2021-09-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_purchase_order_requisition_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='key',
        ),
    ]
