# Generated by Django 3.2.7 on 2021-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_requisition_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Incompleto', 'Incompleto')], default='Pendiente', max_length=20, verbose_name='Estado de producto'),
        ),
    ]
