# Generated by Django 3.2.8 on 2021-11-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_provider_token_apply_date'),
        ('order', '0005_requisition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='provider',
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
            preserve_default=False,
        ),
    ]
