# Generated by Django 3.2.9 on 2021-11-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20211110_0021'),
        ('order', '0006_auto_20211111_0028'),
    ]

    operations = [
    ]
