# Generated by Django 3.2.9 on 2021-11-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_merge_0006_auto_20211110_0021_0006_auto_20211111_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
