# Generated by Django 3.2.9 on 2021-12-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0008_requisition_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_folio', models.CharField(editable=False, max_length=30, verbose_name='Folio')),
                ('invoice_date', models.DateTimeField(editable=False, verbose_name='Fecha Factura')),
                ('amount', models.FloatField(editable=False, verbose_name='Importe')),
                ('client', models.CharField(editable=False, max_length=255, verbose_name='Socio')),
                ('delivery_date', models.DateTimeField(verbose_name='Fecha Entrega')),
                ('xml_file', models.FileField(unique=True, upload_to='invoices/')),
                ('invoice_file', models.FileField(unique=True, upload_to='invoices/')),
                ('extra_file', models.FileField(unique=True, upload_to='invoices/')),
                ('status', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=30, verbose_name='Estado de Factura')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
