# Generated by Django 3.2.9 on 2021-12-20 22:20

import django.core.validators
from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20211217_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='extra_file',
            field=models.FileField(null=True, upload_to=invoices.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(upload_to=invoices.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='xml_file',
            field=models.FileField(upload_to=invoices.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])]),
        ),
    ]
