# Generated by Django 3.2.9 on 2021-12-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20211220_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(verbose_name='Fecha Entrega'),
        ),
    ]
