# Generated by Django 3.2.9 on 2021-12-22 18:34

import django.core.validators
from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='extra_file',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.get_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])]),
        ),
    ]
