# Generated by Django 3.2.10 on 2021-12-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_extra_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reject_reason',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
