# Generated by Django 3.2.10 on 2021-12-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=30, verbose_name='Estado de Factura'),
        ),
    ]
