# Generated by Django 3.2.10 on 2022-01-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
