# Generated by Django 3.2.10 on 2022-01-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_client_responsible',
            field=models.BooleanField(default=True),
        ),
    ]
