# Generated by Django 3.2.9 on 2021-12-15 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140, verbose_name='Título')),
                ('addressee', models.CharField(choices=[('providers', 'providers'), ('clients', 'clients')], default='clients', max_length=15, verbose_name='Destinatarios')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('file_uuid', models.CharField(max_length=36, verbose_name='URL del archivo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
