# Generated by Django 3.2.10 on 2021-12-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='file_uuid',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file_url',
            field=models.URLField(default='', verbose_name='URL del archivo'),
        ),
    ]
