# Generated by Django 3.2.10 on 2022-03-03 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20211221_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio'),
        ),
    ]
