# Generated by Django 3.2.7 on 2021-09-15 01:40

from django.db import migrations

from backend.utils.constants import ADMIN_GROUP, CLIENT_GROUP, PROVIDER_GROUP


# Create initial user roles / groups
def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create([
        Group(name=ADMIN_GROUP),
        Group(name=PROVIDER_GROUP),
        Group(name=CLIENT_GROUP)
    ])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_group),
    ]
