# Generated by Django 3.2.7 on 2021-09-15 01:40

from django.db import migrations


# Create initial user roles / groups
def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create([
        Group(name='Administrador'),
        Group(name='Proveedor'),
        Group(name='Cliente')
    ])


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_group),
    ]
