# Generated by Django 3.2.7 on 2021-10-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='category',
            field=models.CharField(choices=[('Pedidos', 'Pedidos'), ('Facturas', 'Facturas'), ('Cambio de precios', 'Cambio de precios'), ('Saldos', 'Saldos')], max_length=50, verbose_name='Categoría de correo electrónico'),
        ),
    ]
