# Generated by Django 3.2.7 on 2021-09-15 01:40

from django.db import migrations

from backend.utils.constants import (
    REPORTER_GROUP, INVOICE_MANAGER_GROUP,
)


# Create invoice user roles / groups
def create_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.bulk_create([
        Group(name=REPORTER_GROUP),
        Group(name=INVOICE_MANAGER_GROUP),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useremail_category'),
    ]

    operations = [
        migrations.RunPython(create_group),
    ]
